config/routes.rb
NameOfApp::Application.routes.draw do
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  get "users/new"

  root :to => 'static_pages#home'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/signup', to: 'users#new'

end

app/models/product.rb
class Event < ActiveRecord::Base

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible  :name, :email, :password, :password_confirmation, :avatar 

  has_secure_password

  before_save  { |user| user.email = user.email.downcase }
  before_save :create_remember_token 

  validates :name, presence: true, :length => { :maximum => 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[\w+\-.]+\.[a-z]+/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
   has_attached_file :avatar, 
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>" }

private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else

    flash.now[:error] = "Invalid email/password combination"
    render 'new'
  end
  end

  def destroy
    sign_out 
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def signup
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show 
    @user = User.find(params[:id])
  end

  def create 
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "What's Up, Doc!"
      redirect_to (@user)
    else
    render 'new'
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] =  user.remember_token
                                
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<div class="container">


<% flash.each do |key, value| %>
<%= content_tag(:div, value, class: "alert alert-#{key}")  %>
<% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
     <div class="logo_box">
      <%= link_to image_tag("logo.png"), root_path, alt: 'RawAr' %>
    </div>  
       <nav>
         <ul class="nav pull-right">
           <li>
            <%= link_to 'Who We are', root_path %></a>
          </li> 

             <li>
            <%= link_to 'What we do', "#" %></a>
          </li>

            <li>
            <%= link_to 'We do work', "#" %></a>
          </li>

           <% if signed_in? %>
           <li>
            <%= link_to "Users", '#' %>
          </li> 
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user) %></li> 
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul> 
          <li>
            <% else %>
            <li>
              <%= link_to "Sign in", signin_path %>
            </li> 
          <% end %> 
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NameOfApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <%= render 'layouts/error_messages' %>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id= "error-explanation">
    <div class="alert alert-error">
      The form conatains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %>  </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="hero-unit mainbanner"> 
    <div id="keep_still">
    <h1 class="banner_font pull-left">hello.</h1>
    <p class="intro_font">
      This is my fake ass website I'm building. <br />So that I can <a href="#" class="intro-search">Practice Ruby on Rails</a> <br /><a href="#" class="intro-design">and web design</a>
    </p>
    <p class="intro_font">
      Join Us or Die <%= link_to "Sign up", signup_path, class: "intro-rawr" %>
    </p>
  </div>
</div>


<div class="live_feed">  
  <h2 class="live_feed_font"><div id="circle_left"></div>I'm Fucking....<span class="blue_font">Sleeping</span>.  Why Not Send Me An <span class="blue_font">Email?</span><div id="circle_right"></div></h2>
</div>  
<br /><br /><br /><br />

<div class="page">
  <div class="row">
    <div class="span4">
      <%= link_to image_tag('/assets/search-optimisation.png') %>
      <section>
        <h3 class="font_green">Search Engine Optimization</h3>
        <p>We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta ipsum dolor sitta. We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta.</p>
      </section>
    </div>
    <div class="span4">
      <%= link_to image_tag('/assets/web-design.png') %>
      <section><h3 class="font_pink">Web Design</h3>
        <p>We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta.</p>
      </section>
    </div>
    <div class="span4">
      <%= link_to image_tag('/assets/who-we-are.png') %>
      <section><h3 class="blue_font">Who We Are</h3>
        <p>We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta. We love the web and lorem ipsum dolor sitta.</p>
      </section>
    </div>
  </div>

  <div class="grey_section">
    <div class="row">
    <div class="span5">
      <span class="bigWhite">We Optimize</span> I told all you lorem ipsum dolor sitta ipsum dolor sitta ipsum dolor sittaipsum dolor sitta  you get sloppy drunk I stay Whiskey neat.  My shit should be cancelled.  Freaks and Geeks.
      <br /><br />
      <a class="HyperlinkGreen" href="">click here to learn more</a>
    </div>
    <div class="span1 grey_centersection">
      <%= link_to image_tag('/assets/andSymobl.png') %>
    </div>
    <div class="span5 grey_rightsection">
     <span class="bigWhite2">We Design</span> the funk to fit the renegades of rage against the machine. Lorem ipsum dolor sitta Lorem ipsum dolor sitta Lorem ipsum dolor sitta Lorem ipsum dolor sitta Lorem ipsum dolor sitta Lorem ipsum dolor sitta
     <br /><br />
     <a class="HyperlinkPink" href="">click here to learn more</a>
    </div>    
    </div>    
  </div>
  <br /><br /><br /><br />

<div class="bigWhite_pink">My Happy Thoughts</div>
  <br />
  <div class="row">
    <div class="span5">
    <%= link_to image_tag('/assets/happy_thoughts.png'), :class => "float-left" %>
  </div>
    <%= link_to image_tag('/assets/_overlay_1801.png') %>
    <%= link_to image_tag('/assets/_overlay_1802.png') %> 
    <%= link_to image_tag('/assets/_overlay_1804.png') %> 
    <br /> <br /> <br />  
    <%= link_to image_tag('/assets/_overlay_1805.png') %>
    <%= link_to image_tag('/assets/_overlay_1806.png') %> 
    <%= link_to image_tag('/assets/_overlay_1803.png') %>      
</div>
  <br /><br /><br />
  <div class="bigWhite_blue">Why Choose Us?</div>
  <br /><br />
  <div class="row">
  <div class="span4 left_bar_padding">
    <div class="icon_image">
      <%= link_to image_tag('/assets/speech_bubbles.png') %>
    </div>
   
      <p><b>I am Zim!  Waffles Waffles Waffles.</b>  Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. </p>
    

    <br />
    <div class="icon_image">
      <%= link_to image_tag('/assets/people_icon.png') %>
    </div>
   
      <p><b>I am Zim!  Waffles Waffles Waffles.</b>  Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. </p>
    

    <br />

   <div class="icon_image">
      <%= link_to image_tag('/assets/heart_icon.png') %>
    </div>
   
      <p><b>I am Zim!  Waffles Waffles Waffles.</b>  Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. Lorem ipsum dolor sitta. </p>
    

    <br />
        
  </div>

  <div class="span4">
    <p><small>3RD JULY 2012</small> <br />
    <span class="blue_font">A New Kind of Star Wars Rules</span></p>
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 

    <br />  
    <hr>

    <p><small>2RD JUNE 2012</small> <br />
    <span class="blue_font">Holy Shit I Love Batman</span></p>
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 


  </div>

  <div class="span4 float-right">
    <p><small>3RD JULY 2012</small> <br />
    <span class="font_green">A New Kind of Star Wars Rules</span></p>
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 

    <br />  
    <hr>

    <p><small>2RD JUNE 2012</small> <br />
    <span class="font_green">Holy Shit I Love Batman</span></p>
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta. 
    I am Zim!  Waffles Waffles Waffles.  Lorem ipsum dolor sitta.   
  </div>


</div>
  <br />
  
    

</div>


 

app/views/static_pages/signup.html.erb
<h1>StaticPages#signup</h1>
<p>Find me in app/views/static_pages/signup.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container">
<h1>Sign up</h1>

<%= render 'shared/error_messages' %>

<div class="row">
  <div class="span6 offset3">

<%= form_for(@user, :html => { :multipart => true }) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>


      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>  

       <div class="field">
  <%= f.file_field :avatar %>
  </div>  

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>


    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<%= image_tag @user.avatar.url %>
<%= image_tag @user.avatar.url(:medium) %>
<%= image_tag @user.avatar.url(:thumb) %> 
<h1><%= @user.name %></h1>

</div>